version: "3"
services:
  agilekip:
    container_name: agilekip
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - main
    logging:
      options:
        max-size: 10m
        max-file: "3"
    restart: unless-stopped
    # environment:
    #   - HOST=$BACKEND_HOST
    ports:
      - "$PORT:8080"
    volumes:
      - "./jhipster:/home/jhipster/app"
    command: tail -f /dev/null

networks:
  main:
